---
title: "Few Article Summary"
author: "Christopher Witt"
date: "September 22, 2015"
output: html_document
---

"Effictively Communicating Numbers:"

This article dealt with how one should effectively communicate numbers even if they have no background in statistics. To overcome this barrier the author sets 6 goals/ guidelines that should be met in order to effectively communicate data from one person to another. People must learn to match a message they are trying to communicate to the proper display and in turn should design each component of the graph so that the data speaks clearly. The six stages that the author proposes that individuals should follow begin with determining the message and to identify the data necessary to communicate it. Often times this is the hardest step because it requires you to really think about what you want to say with the numbers you have, in order to communicate the data you must know what the data means and what’s important. The second step is to determine if a table, graph, or combination of both is needed to communicate your message. Here the creators must ask themselves if the data is to be used to compare and look up individual values or if it needs to be precise. The third step is to determine the best ways to encode values; the creator needs to know if they are following nominal comparisons, time-series comparisons or ranking among many others. Once this step is met the fourth step is to determine where to display each value. Here, you take what you have concluded in step 3 and come to the best means for communication those concepts. The fifth step deals with determining the best design for the remaining values. This step deals with determining how to effectively design your graph or table, which includes how to incorporate the scales and texts; basically your main concern should be with the placement and visual appearance of items. The final step, step 6, is concerned with determining if particular data should be displayed above the rest. Here you should focus on highlighting data based on its importance, if one set of data is the primary focus of the visualization then it should be displayed in such a way that highlights it above the lesser important sets. To effectively highlight data you should use color to properly communicate importance. Lastly the author talked about the importance of using 2-dimensional displays because they are triggering the most powerful attributes of visual perception. Digging more deeper into the question of displays, the author emphasizes that the best objects for encoding data are lines, points, bars and boxes because they allow us to effectively understand the data while minimizing unnecessary perceptual variables. 